name: Check Checkboxes in Pull Request Description
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  checkbox-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Checkboxes
        uses: actions/checkout@v2

      - name: Check Checkboxes in Description
        run: |
          description=$(curl -sSL ${{ github.event.pull_request.url }} | jq -r '.body')
          if echo "$description" | grep -E '\[ \]' >/dev/null; then
            echo "Not all checkboxes are checked. Merge request not allowed."
            exit 1
          else
            echo "All checkboxes are checked. Proceed with the merge."
            exit 0
          fi
