name: Check Checkboxes in Pull Request Description
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  checkbox-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Checkboxes
        uses: actions/checkout@v2
      - name: Check Checkboxes in Description
        run: |
          description=$(cat ${{ github.event.pull_request.body_path }})
          if [[ "$description" =~ \[x\] && ! "$description" =~ \[ \] ]]; then
            echo "All checkboxes are checked. Proceed with the merge."
            exit 0
          else
            echo "Not all checkboxes are checked. Merge request not allowed."
            exit 1
          fi
