name: Check Checkboxes in Pull Request Description
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  checkbox-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Checkboxes
        uses: actions/checkout@v2

      - name: Check Checkboxes in Description
        run: |
          # Get the pull request description
          description=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.pull_request.url }} | jq -r '.body')

          # Check if the description contains any unchecked checkboxes [ ]
          if echo "$description" | grep -E '\[ \]' >/dev/null; then
            echo "Not all checkboxes are checked. Merge request not allowed."
            exit 1
          else
            echo "All checkboxes are checked. Proceed with the merge."
          fi
